apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisco-tunnel
  namespace: ciscotechnologies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cisco-tunnel
  template:
    metadata:
      labels:
        app: cisco-tunnel
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: ["cloudflared", "tunnel", "--no-autoupdate", "run"]
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cisco-secrets
                  key: eyJhIjoiOWZkODA2YzExMDhiZGY1Mzc4Zjg4OGM1MWVlZGM1MmIiLCJ0IjoiOGJlOWI1NzQtODU1OS00YWUwLWJmMGUtYjQyMmE4NDE2NzRlIiwicyI6Ik1UazNZemcwTXpRdE5HRTRZeTAwTldJekxUaG1OamN0Wm1RNFpqSmpNall5WXpCbCJ9