version: '3.8'

services:
  # ------------------------------------
  # 1. The Database Layer (PostgreSQL)
  # ------------------------------------
  db:
    image: postgres:15-alpine
    container_name: cisco-db
    restart: always
    environment:
      POSTGRES_USER: cisco_admin
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: cisco_architecture
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cisco-net

  # ------------------------------------
  # 2. The Web Layer (Nginx Frontend)
  # ------------------------------------
  web:
    image: nginx:alpine
    container_name: cisco-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
      # Add this line below to load the reverse proxy rules:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
    networks:
      - cisco-net
    depends_on:
      - api

  # ------------------------------------
  # 3. The API Layer (Python/Flask)
  # ------------------------------------
  api:
    build: ./api
    container_name: cisco-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - cisco-net

  # ------------------------------------
  # 4. The Cloudflare Edge Tunnel
  # ------------------------------------
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cisco-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOWZkODA2YzExMDhiZGY1Mzc4Zjg4OGM1MWVlZGM1MmIiLCJ0IjoiOGJlOWI1NzQtODU1OS00YWUwLWJmMGUtYjQyMmE4NDE2NzRlIiwicyI6Ik1UazNZemcwTXpRdE5HRTRZeTAwTldJekxUaG1OamN0Wm1RNFpqSmpNall5WXpCbCJ9
    command: tunnel --no-autoupdate run
    networks:
      - cisco-net

# ------------------------------------
# 5. Persistent Storage & Networks
# ------------------------------------
volumes:
  pgdata:

networks:
  cisco-net:
    driver: bridge