apiVersion: v1
kind: Secret
metadata:
  name: cisco-secrets
  namespace: ciscotechnologies
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Password123!"
  FLASK_SECRET_KEY: "change-this-to-a-long-random-string-in-production"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "CiscoAdmin123!"
  TUNNEL_TOKEN: "eyJhIjoiOWZkODA2YzExMDhiZGY1Mzc4Zjg4OGM1MWVlZGM1MmIiLCJ0IjoiOGJlOWI1NzQtODU1OS00YWUwLWJmMGUtYjQyMmE4NDE2NzRlIiwicyI6Ik1UazNZemcwTXpRdE5HRTRZeTAwTldJekxUaG1OamN0Wm1RNFpqSmpNall5WXpCbCJ9"