# secret-template.yaml
# DO NOT add real values here
# Secrets are injected by Jenkins at deploy time
# See Jenkinsfile for how secrets are created

apiVersion: v1
kind: Secret
metadata:
  name: cisco-secrets
  namespace: ciscotechnologies
type: Opaque
stringData:
  POSTGRES_PASSWORD: "INJECTED_BY_JENKINS"
  FLASK_SECRET_KEY: "INJECTED_BY_JENKINS"
  ADMIN_USERNAME: "INJECTED_BY_JENKINS"
  ADMIN_PASSWORD: "INJECTED_BY_JENKINS"
  TUNNEL_TOKEN: "INJECTED_BY_JENKINS"