apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ciscotechnologies
spec:
  storageClassName: local-path

  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: 10Gi