apiVersion: v1
kind: Service
metadata:
  name: cisco-postgres-service
  namespace: ciscotechnologies
spec:
  selector:
    app: cisco-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP