from flask import Flask, request, jsonify
import psycopg2
import os
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

DB_USER = os.getenv("POSTGRES_USER", "cisco_admin")
DB_PASS = os.getenv("POSTGRES_PASSWORD", "Password123!")
DB_NAME = os.getenv("POSTGRES_DB", "cisco_architecture")
DB_HOST = os.getenv("DB_HOST", "db")

def get_db_connection():
    return psycopg2.connect(host=DB_HOST, database=DB_NAME, user=DB_USER, password=DB_PASS)

def init_db():
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute('''
        CREATE TABLE IF NOT EXISTS tickets (
            id SERIAL PRIMARY KEY,
            requester VARCHAR(100),
            email VARCHAR(100),
            severity VARCHAR(20),
            category VARCHAR(50),
            description TEXT,
            timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ''')
    conn.commit()
    cur.close()
    conn.close()

# ROUTE 1: Create a ticket and return the ID
@app.route('/api/ticket', methods=['POST'])
def create_ticket():
    data = request.json
    conn = get_db_connection()
    cur = conn.cursor()
    
    # We added 'RETURNING id' to grab the exact ticket number generated by the database
    cur.execute(
        'INSERT INTO tickets (requester, email, severity, category, description) VALUES (%s, %s, %s, %s, %s) RETURNING id',
        (data['requester'], data['email'], data['severity'], data['category'], data['description'])
    )
    new_ticket_id = cur.fetchone()[0]
    conn.commit()
    cur.close()
    conn.close()
    
    return jsonify({"status": "success", "ticket_id": new_ticket_id}), 201

# ROUTE 2: Fetch all tickets for the Internal Admin Portal
@app.route('/api/tickets', methods=['GET'])
def get_tickets():
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute('SELECT id, requester, email, severity, category, description, timestamp FROM tickets ORDER BY timestamp DESC;')
    tickets = cur.fetchall()
    cur.close()
    conn.close()
    
    ticket_list = []
    for t in tickets:
        ticket_list.append({
            "id": t[0], "requester": t[1], "email": t[2], 
            "severity": t[3], "category": t[4], "description": t[5], "timestamp": t[6]
        })
        
    return jsonify(ticket_list), 200

if __name__ == '__main__':
    init_db()
    app.run(host='0.0.0.0', port=5000)